### PR TITLE
Replace `failwith` with errors, close #392

### LINKED ISSUE #392: Replace all `failwith` with errors
The code right now fails randomly in places with `failwith`. These should all be turned into proper error messages. Also, all `asserts` should be replaced with an error which either raises an assert or reports an "impossible thiing happened" error, depending on a configuration parameter.

### PR DESCRIPTION
**Pull request by andrejbauer**

### CODE REVIEW

File: src/nucleus/jdg.ml [hunk 1]
```diff
@@ -804,11 +801,10 @@ let occurs_eq_term_abstraction = occurs_abstraction TT.assumptions_eq_term
...
 let apply_abstraction inst_u sgn abstr e0 =
   match abstr with
-  | TT.NotAbstract _ ->
-     failwith "Tried to apply an argument to a NotAbstract. Type-checking should prevent this!"
+  | TT.NotAbstract _ -> TT.error TT.AbstractionExpected
   | TT.Abstract (x, t, abstr) ->
      begin match TT.alpha_equal_type t (type_of_term sgn e0) with
-     | false -> failwith "bar"
+     | false -> TT.error TT.InvalidSubstitution
      | true ->  TT.instantiate_abstraction inst_u e0 abstr
```
Comment (haselwarter) [inline src/nucleus/jdg.ml]: Should we tell the user what type we expected / found ?

File: src/nucleus/jdg.ml [hunk 2]
```diff
@@ -804,11 +801,10 @@ let occurs_eq_term_abstraction = occurs_abstraction TT.assumptions_eq_term
 
 let apply_abstraction inst_u sgn abstr e0 =
   match abstr with
-  | TT.NotAbstract _ ->
-     failwith "Tried to apply an argument to a NotAbstract. Type-checking should prevent this!"
+  | TT.NotAbstract _ -> TT.error TT.AbstractionExpected
```
Comment (haselwarter) [inline src/nucleus/jdg.ml]: This should be a failwith / assert false because AML type-checking keeps count of abstraction levels.

File: src/runtime/matching.ml [hunk 3]
```diff
@@ -1,4 +1,4 @@
-
+a
```
Comment (haselwarter) [inline src/runtime/matching.ml]: Typo

File: src/runtime/matching.ml [hunk 4]
```diff
@@ -228,7 +228,10 @@ and collect_args env xvs ps vs =
      end in
      collect_args env xvs ps vs
 
-  | [], _::_ | _::_, [] -> assert false
+  | [], _::_ | _::_, [] ->
+     (*** XXX should we raise an error instead? A well-typed program should never get here,
+          but for an untyped one it kind of makes sense to just fail the match. *)
+     raise Match_fail
```
Comment (haselwarter) [inline src/runtime/matching.ml]: We will never run untyped programs. At most, there's external's "magic", but I don't see how it makes sense to fail the match here in that case.

File: src/nucleus/jdg.ml [hunk 5]
```diff
@@ -383,8 +387,8 @@ let match_arguments sgn (premises : Rule.premise list) (arguments : argument lis
        (* The arguments must _not_ be reversed because we refer to them by meta-variable
           de Bruijn indices, and therefore the last argument must have index 0. *)
        args_out
-    | [], _::_ -> failwith "too many arguments"
-    | _::_, [] -> failwith "too few arguments"
+    | [], _::_ -> TT.error TT.TooManyArguments
+    | _::_, [] -> TT.error TT.TooFewArguments
```
Comment (haselwarter) [inline src/nucleus/jdg.ml]: These should be assert false / failwith, because src/parsing/desugar.ml:772 already checks arities of rules.

**Comment by andrejbauer** [comment]
@haselwarter and I looked over these changes together, he says I can push the merge button.
